### ISSUE TITLE
Shutdown kryo when webapp/tomcat is stopping

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#145]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 15, 2011 22:15:13_

When the tomcat running msm with kryo transcoder is stopped, there's a message

SEVERE: The web application [] created a ThreadLocal with key of type [com.esotericsoftware.kryo.Kryo$1] (value [com.esotericsoftware.kryo.Kryo$1@348dcd5d]) and a value of type [com.esotericsoftware.kryo.Context] (value [com.esotericsoftware.kryo.Context@49a5af9f]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.

This should be fixed by stopping kryo when the manager (msm) is stopped.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=102_

**Comment by google-code-exporter** [comment]
_From [st...@regattacentral.com](https://code.google.com/u/118417951878597527735/) on August 30, 2013 11:07:18_

I'm seeing this issue whenever I upload a new jar and reload the webapp.   Any update/ETA on a fix?   

Cheers,
Steve

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 30, 2013 13:18:26_

I had a look at this last weekend and it doesn't seem to be fixable that easily.
I'd rather invest time to upgrade to kryo 2 (and what's still needed in kryo-serializers for this), then this annoyance is automatically gone.

**Comment by google-code-exporter** [comment]
_From [st...@regattacentral.com](https://code.google.com/u/118417951878597527735/) on September 09, 2013 06:38:22_

that makes sense.  In fact, I actually was curious about kryo 2 support.  Completely agree that this should be deferred.
