### ISSUE TITLE
No validity info stored for non-sticky sessions and memcachedNodes config without node-part

### ISSUE THREAD

**Issue by google-code-exporter** [magro/memcached-session-manager#155]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 27, 2011 12:47:56_

For a memcachedNodes configuration without node part (e.g. memcachedNodes="localhost:11211", added with feature #105) and non-sticky sessions (sticky="false") the following warning is logged for each request:

  WARN [de.javakaffee.web.msm.LockingStrategyAuto] No validity info available for session

This happens for all lockingModes.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=112_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 27, 2011 03:59:55_

Fixed in branches master and membase-sasl.

**Status:** Fixed  
  **Labels:** Milestone-1.6.0

**Comment by google-code-exporter** [comment]
_From [ache...@gmail.com](https://code.google.com/u/109210298033469947599/) on November 20, 2013 17:07:37_

Hello,we used non-sticky sessions to save httpSession with memcached session.
But when user access the site,  the tomcat is logged:

Nov 21, 2013 9:01:16 AM de.javakaffee.web.msm.LockingStrategy onAfterLoadFromMemcached
WARNING: No validity info available for session 4C96C472795F4487299B0A85DB061EF6-n1

It happens sometimes.
And the result is in another tomcat, it cannot get this session.
What changes should be change?

**Comment by google-code-exporter** [comment]
_From [ache...@gmail.com](https://code.google.com/u/109210298033469947599/) on November 20, 2013 17:10:16_

Our memcached info is :
stats
STAT pid 2236
STAT uptime 44965
STAT time 1384996137
STAT version 1.4.5
STAT pointer_size 64
STAT rusage_user 1.916708
STAT rusage_system 7.047928
STAT curr_connections 8
STAT total_connections 806
STAT connection_structures 10
STAT cmd_get 58984
STAT cmd_set 46265
STAT cmd_flush 0
STAT get_hits 37170
STAT get_misses 21814
STAT delete_misses 28
STAT delete_hits 817
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT auth_cmds 0
STAT auth_errors 0
STAT bytes_read 1478750266
STAT bytes_written 3456132714
STAT limit_maxbytes 6291456000
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 54784273
STAT curr_items 1094
STAT total_items 35983
STAT evictions 0
STAT reclaimed 8779
END

**Comment by aishydevil12286** [comment]
We are facing the same issue. can you please share what was the issue all about and how was this resolved for you.
