### ISSUE TITLE
package split between memcached session manager jars

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#164]
_From [guy.vac...@gmail.com](https://code.google.com/u/107317770144216365448/) on February 16, 2012 17:54:20_

<b>What steps will reproduce the problem?</b>
1. classes of the same package are located in 2 jars (memcached-session-manager-1.6.0.jar and memcached-session-manager-tc6-1.6.0.jar)&#13;
2. in case of Java EE serveur (OSGi based like Glassfish or JOnAS), those jars are installed as bundles. The problem is that the bundle process export only one package&#13;
3. then a java.lang.NoClassDefFoundError occurs at deployment (de.javakaffee.web.msm.MemcachedSessionService$SessionManager not found by memcached-session-manager-tc6-1.6.0 -bundle !-)&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
is it possible to merge the 2 jars in one&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
1.6.0 &#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=121_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 17, 2012 06:49:48_

I'll see if I can package the classes from core into tc6/tc7 jars.

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by google-code-exporter** [comment]
_From [mikenere...@gmail.com](https://code.google.com/u/116700814891991186682/) on June 13, 2012 07:22:04_

Martin suggested (<a href="https://groups.google.com/d/msg/memcached-session-manager/67O-vjy6Mtk/2G_QUVW-SOcJ" rel="nofollow">https://groups.google.com/d/msg/memcached-session-manager/67O-vjy6Mtk/2G_QUVW-SOcJ</a>) this may be resolvable via the use of the Maven Shade plugin <a href="http://maven.apache.org/plugins/maven-shade-plugin/" rel="nofollow">http://maven.apache.org/plugins/maven-shade-plugin/</a>&#13;
&#13;
The Maven Assembly plugin might also do the trick <a href="http://maven.apache.org/plugins/maven-assembly-plugin/" rel="nofollow">http://maven.apache.org/plugins/maven-assembly-plugin/</a>

**Comment by google-code-exporter** [comment]
_From [mikenere...@gmail.com](https://code.google.com/u/116700814891991186682/) on June 13, 2012 07:30:13_

For clarification, the current packaging requires that

"Independent of the chosen serialization strategy you always need the memcached-session-manager-${version}.jar and either memcached-session-manager-tc6-${version}.jar for tomcat6 or memcached-session-manager-tc7-${version}.jar for tomcat7."

Is the goal that we only need to include tc6 or tc7 OR is the goal that we still need both, but that no overlapping classes exist in tc6 or tc7?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 13, 2012 08:05:44_

I think the easiest would be to have only tc6/tc7 jars.

This is easier as it does not need code changes but only some pom configuration and it's also easier for users as they have to manage 1 jar less.

We could even pull the spymemcached jar into the shaded one (with the disadvantage that users cannot update spymemcached jar independently from msm).

**Comment by magro** [comment]
Reopen if needed.
