### ISSUE TITLE
Non-sticky sessions + liferay + lockingMode "auto" or "uri" cause problems.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#170]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 28, 2012 14:06:59_

As reported in <a href="http://groups.google.com/group/memcached-session-manager/t/1efe122855ee415f" rel="nofollow">http://groups.google.com/group/memcached-session-manager/t/1efe122855ee415f</a>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=127_

**Comment by google-code-exporter** [comment]
_From [denis.si...@gmail.com](https://code.google.com/u/105548482992247672762/) on December 18, 2014 00:15:40_

Hi Martin, the related thread it's a bit long and it's related to many different configurations. Which configurations do you suggest ATM to get a Liferay instance with Tomcat 7 working correctly ?

Thanks,
Regards,
Denis.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 21, 2014 13:19:28_

I'm sorry, but I don't know which config will work with liferay.
