### ISSUE TITLE
Nonsticky sessions + liferay: Session is still used by another request

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#171]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 31, 2012 22:57:31_

When running liferay 6.0.5 with msm + nonsticky sessions after some time and clicking (logged in) a session seems to be staying locked. This is indicated by output like the following and -vv memcached output that does not show any more interaction with this session.

Mar 31, 2012 8:50:18 PM de.javakaffee.web.msm.MemcachedSessionService backupSession
FINE: Session 8FF89738A4C8987797285A751907889E-n1 is still used by another request, skipping backup and (optional) lock handling/release.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=128_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on March 31, 2012 14:14:16_

Just tried to reproduce and it took rather long until this occurred again (this time after clicking on control-panel left top).
