### ISSUE TITLE
Exception in BackupSessionTask.call is ignored for sessionBackupAsync=true and sticky sessions

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#173]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 12, 2012 00:23:00_

I found this during a code review for a request on the mailing list: <a href="http://groups.google.com/group/memcached-session-manager/browse_thread/thread/bd5eee1bca564369" rel="nofollow">http://groups.google.com/group/memcached-session-manager/browse_thread/thread/bd5eee1bca564369</a>&#13;
&#13;
The BackupSessionTask.call method does not handle exceptions, and the future result is only accessed in BackupSessionService.backupSession if !sessionBackupAsync. The future result is also not accessed by any other component in sticky mode.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=130_

**Comment by magro** [comment]
This was already resolved in commit dd2b03fc.
