### ISSUE TITLE
When the application set a cookie starting with JSESSIONID the session backup is skipped

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#174]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 19, 2012 15:38:19_

This was reported on the mailing list:
<a href="http://groups.google.com/group/memcached-session-manager/browse_thread/thread/c9392e0ae69a62b8" rel="nofollow">http://groups.google.com/group/memcached-session-manager/browse_thread/thread/c9392e0ae69a62b8</a>&#13;
&#13;
This is an example for a Set-Cookie header:&#13;
&#13;
FINE: Request finished, with Set-Cookie header: JSESSIONID_LAST_REQUEST=1334667824384; Version=1; Comment="datcre=Tue Apr 17 15:03:44 CEST 2012"; Path=/

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=131_

**Comment by magro** [comment]
Please reopen if needed.
