### ISSUE TITLE
no SubList in IBM jdk. kryo serializer will not work.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#175]
_From [hightec4...@gmail.com](https://code.google.com/u/106748054857228203149/) on April 27, 2012 10:36:52_

<b>What steps will reproduce the problem?</b>
1.download ibm jdk(on s390x) and install.&#13;
2.use MSM to share tomcat session&#13;
3.see catalina.out with Exception[ Class Not Found: java.util.SubList]&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
in tomcat/logs catalina.out,  Exception[ Class Not Found: java.util.SubList]&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
version.1.6.1. on ibm s390x.&#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=132_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 27, 2012 01:43:15_

<i>(No comment was entered for this change.)</i>

**Status:** Accepted

**Comment by magro** [comment]
Should be solved using a custom transcoder or by improving kryo.
