### ISSUE TITLE
multiple parallel requests for the same session with msm has problem

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#192]
_From [xueshufe...@163.com](https://code.google.com/u/116881990499226553473/) on September 17, 2012 04:28:55_

I use tomcat7, my config is:
<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager" 
memcachedNodes="n1:localhost:11211" 
requestUriIgnorePattern=".*\.(png|gif|jpg|css|js)$" 
sticky="false"
lockingMode="auto"
sessionBackupTimeout="10000"
operationTimeout="10000"
customConverter="com.zte.mobile.serializer.CustomKryoRegistration"
sessionBackupAsync= "false"
copyCollectionsForSerialization="false" 
transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory" />
msm version is:
memcached-session-manager-1.6.2.jar
memcached-session-manager-tc7-1.6.2.jar
spymemcached-2.8.4.jar

   my application has many ajax requests when login is sucessed; when two requests use msm at the same time,  one request of them  save session using session.setAttibute do not work, the attibute do not save to mamcached.
  from the log ,I find first request load session from the memcached, second request do not load session, because the session has load by first request. but second request has not end, first request save session to memcached. I think first request do not save, second request save is corect;

   so I read the source ,I find same bugs; 
  memcachedsessionservice.java  the function findSession , I modify it; 

    public MemcachedBackupSession findSession( final String id ) throws IOException {
        MemcachedBackupSession result = _manager.getSessionInternal( id );
        if ( result != null ) {
            // TODO: document ignoring requests and container managed authentication
            // -> with container managed auth protected resources should not be ignored  && !isContainerSessionLookup()
            // TODO: check ignored resource also below
            _log.info( " log==== findSession"  );
            if (!_sticky && !_trackingHostValve.isIgnoredRequest() ) {
			_log.info( "log==== findSession ok"  );	                 result.registerReference();
            }
        }

 I modify it, then test is very good.

some one can tell me  is my method  right?

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=151_

**Comment by google-code-exporter** [comment]
_From [xueshufe...@163.com](https://code.google.com/u/116881990499226553473/) on September 16, 2012 19:32:21_

if (!_sticky && !_trackingHostValve.isIgnoredRequest() && !isContainerSessionLookup()
) 

I modify it such:

if (!_sticky && !_trackingHostValve.isIgnoredRequest() )

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 17, 2012 01:01:03_

The best would be to have a test that reproduces the issue to see if there is an issue and if this is a valid fix.
NonStickySessionsIntegrationTest contains several tests that cover cases like this (<a href="https://github.com/magro/memcached-session-manager/blob/master/core/src/test/java/de/javakaffee/web/msm/integration/NonStickySessionsIntegrationTest.java" rel="nofollow">https://github.com/magro/memcached-session-manager/blob/master/core/src/test/java/de/javakaffee/web/msm/integration/NonStickySessionsIntegrationTest.java</a>).

**Comment by google-code-exporter** [comment]
_From [xueshufe...@163.com](https://code.google.com/u/116881990499226553473/) on September 17, 2012 19:25:19_

the function testParallelRequestsDontCauseDataLoss and testParallelRequestsToSameTomcatInstanceIssue111  may use http1.1， it must use connection : keep-alive。

my application use nginx+tomcat。 nginx use “connection：close” default。
my pressure test result is：
connect：close，      failure rate is 50%
connect：keep-alive， failure rate  is 4%
when connect：keep-alive， failure rate is  small， the test case maybe don't cover it。

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 18, 2012 14:32:05_

So the test has to be altered to also test with connection:close, right? I'll check this as soon as I have time (right now I'm under high workload), of course you're also invited to change/extend the test to make this issue reproducable / testable.

**Comment by google-code-exporter** [comment]
_From [shaikirf...@gmail.com](https://code.google.com/u/111101869168605938405/) on May 25, 2013 06:13:46_

Hi,

Am facing the same issue in multiple tabs and raised a defect here issue id(164).
Even though changing the code  to
if (!_sticky && !_trackingHostValve.isIgnoredRequest() )
in memcachedsessionservice.java am facing the issue. Please help me.

**Comment by google-code-exporter** [comment]
_From [zheng.gu...@gmail.com](https://code.google.com/u/105201542052703221351/) on November 11, 2014 00:03:38_

xueshuf...,
Hello, I saw you issue. Could I ask you some question ?

**Comment by magro** [comment]
Please reopen if needed.
