### ISSUE TITLE
Support pluggable validity serializer

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#201]
_From [downch...@gmail.com](https://code.google.com/u/115424359274750685835/) on April 05, 2013 10:04:04_

Currently the flexjson serializer seems only to serialize the session data. Validity information is still handled via custom byte[] processing in the main package of memcached-session-manager. This results in some data being sent to memcached as binary and some as json (with that particular serializer).

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=160_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 05, 2013 01:18:59_

This would be a good improvement, pull requests highly appreciated! :-)

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by google-code-exporter** [comment]
_From [downch...@gmail.com](https://code.google.com/u/115424359274750685835/) on April 05, 2013 04:22:01_

Does the current JSON package actually save raw json to memcache or is it passed through some kind of deflate or other binary filter? I switched over to Jackson for JSON but I'm still getting binary data in the Memcached sessions.

**Comment by google-code-exporter** [comment]
_From [downch...@gmail.com](https://code.google.com/u/115424359274750685835/) on April 05, 2013 16:55:45_

For anyone reading, these are the two files to tweak.

core/src/main/java/de/javakaffee/web/msm/TranscoderService.java
core/src/main/java/de/javakaffee/web/msm/SessionValidityInfo.java

TranscoderService prepends a byte array of serializeSessionFields before the transcoder  data. SessionValidityInfo is the simple validity:* key, and is easy to convert. No promises on submitting a pull request, but I'll try to get there.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on April 06, 2013 00:11:47_

IIRC spymemcached applies compression as soon as some threshold is exceeded, you might want to be able to influence this.

**Comment by google-code-exporter** [comment]
_From [downch...@gmail.com](https://code.google.com/u/115424359274750685835/) on April 07, 2013 04:22:46_

For my use, I also had to add key prefixes to the memcached set calls and some instanceof String checks on a few memcached get lines. spymemcached does need compression turned off for other use cases (my strings are small enough); it's mentioned in a thread to use:

MemcachedClient c = new MemcachedClient(new InetSocketAddress("127.0.0.1", 11211));
SerializingTranscoder serializingTranscoder = new SerializingTranscoder();
serializingTranscoder.setCompressionThreshold(Integer.MAX_VALUE);
c.set("testkey", 3600, "testvalue", serializingTranscoder);


<a href="https://groups.google.com/d/msg/spymemcached/tRD_lSEdXdk/RcVrWaByNJEJ" rel="nofollow">https://groups.google.com/d/msg/spymemcached/tRD_lSEdXdk/RcVrWaByNJEJ</a>

**Comment by google-code-exporter** [comment]
_From [downch...@gmail.com](https://code.google.com/u/115424359274750685835/) on April 07, 2013 19:22:33_

SessionIdFormat should be used more often. It does carry createLockName and createBackupKey. It ought to handle creating a bare key as well as any other keys used with memcached.

**Comment by magro** [comment]
Please reopen if needed.
