### ISSUE TITLE
msm + jsf + failover node = This XML file does not appear to have any style information associated with it

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#210]
_From [maxtorz...@gmail.com](https://code.google.com/u/107962858049927317676/) on July 09, 2013 22:34:41_

<b>What steps will reproduce the problem?</b>
1.- Install two tomcat instances in separate servers &#13;
2.- Configure LoadBalancing with mod_jk in other server (sticky sessions=true)&#13;
3.- Configure two memcached nodes with sticky=true&#13;
4.- start tomcat servers&#13;
5.- Launch web aplications &#13;
6.- Testing loadbalancing and session replication stopping one memcached node (the one is serving the aplication)&#13;
7.- trying to navigate to another page the Error is shown:&#13;
"This XML file does not appear to have any style information associated with it. The document tree is shown below."&#13;
8.-After a few seconds, I navigate to another page, and the page is rendered.&#13;
&#13;
Is there a way to prevent this error? &#13;
&#13;
extra configurations:&#13;
&#13;
context.xml&#13;
&lt;Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"&#13;
    sticky="true"&#13;
    memcachedNodes="n1:192.168.1.6:11211,n2:192.168.1.3:11211"&#13;
    failoverNodes="n2"&#13;
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"&#13;
    transcoderFactoryClass="de.javakaffee.web.msm.JavaSerializationTranscoderFactory"&#13;
    /&gt;&#13;
&#13;
I also got mapped in each application web.xml the following:&#13;
&lt;servlet-mapping&gt;&#13;
        &lt;servlet-name&gt;Faces Servlet&lt;/servlet-name&gt;&#13;
        &lt;url-pattern&gt;*.xhtml&lt;/url-pattern&gt;&#13;
        &lt;url-pattern&gt;*.jsf&lt;/url-pattern&gt;&#13;
        &lt;url-pattern&gt;*.faces&lt;/url-pattern&gt;&#13;
        &lt;url-pattern&gt;/faces/*&lt;/url-pattern&gt;&#13;
    &lt;/servlet-mapping&gt;&#13;
&#13;
&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=169_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 19, 2013 03:03:12_

Discussed here:
<a href="https://groups.google.com/d/msg/memcached-session-manager/r8A_V5I-e-E/Yhwj050WZiIJ" rel="nofollow">https://groups.google.com/d/msg/memcached-session-manager/r8A_V5I-e-E/Yhwj050WZiIJ</a>

**Comment by magro** [comment]
Closed due to inactivity / missing feedback on the mailing list.
