### ISSUE TITLE
Issue in parallel clustering on form submition jboss, tomcat with chrome browser.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#216]
_From [sandeepchougule45@gmail.com](https://code.google.com/u/sandeepchougule45@gmail.com/) on August 13, 2013 07:30:47_

<b>What steps will reproduce the problem?</b>
1. Request the url (sample.do)&#13;
2. Fill the form for 2, 3 times, 4th time form is not submitting its making all form filed values to blank and opening the same page.&#13;
3. If we clear the cache also and try to submit the form is not getting submitted.&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
From the form it should go to the Action class to save the data but its calling the first action class nd same page is getting loaded.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
We are using Jboss4.2, Apache 2.2 web server.&#13;
OS: windows 2003, with 2 machines each having 4 instances.&#13;
&#13;
<b>Please provide any additional information below.</b>
Only on chrome the session id is getting changed nd form is not getting submitted.&#13;
&#13;
Request you all to please help.&#13;
Thanks &#13;
Sandeep Chougule.&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=175_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 18, 2013 11:55:20_

Does this also happen with tomcat 6/7?
I'm sorry to say that jboss is not supported.
