### ISSUE TITLE
Memcached sessions are flushed, if one tomcat is restarated

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#220]
_From [crudolf....@googlemail.com](https://code.google.com/u/117158638773355660223/) on September 24, 2013 11:04:51_

<b>What steps will reproduce the problem?</b>
1. I am running 2 tomcat instances using memcached-session-manager.&#13;
2. Logging in at tomcat 1.&#13;
3. Restarting tomcat 2.&#13;
4. Getting logged out of tomcat 1, as soon as tomcat 2 is up and running.&#13;
&#13;
Expected result: Staying logged in at both servers.&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=179_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on September 24, 2013 08:51:10_

Please post your msm configuration, and also configure debug logging as described by <a href="https://code.google.com/p/memcached-session-manager/wiki/SetupAndConfiguration#Configure_logging" rel="nofollow">https://code.google.com/p/memcached-session-manager/wiki/SetupAndConfiguration#Configure_logging</a> and provide the log output for the different steps (for each tomcat). Also run memcached with -vv and provide memcached output for each step.
