### ISSUE TITLE
Update to kryo 1.0.6

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#230]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 20, 2013 23:50:45_

See also <a title="Deserialization fails on ConcurrentHashMap in Spring User object" href="/p/memcached-session-manager/issues/detail?id=145">issue #145</a> - kryo 1 now provides a TreeMapSerializer that solves #145 (kryo 1 still needs some work regarding registration of the TreeMapSerializer).

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=189_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on December 20, 2013 14:55:48_

<i>(No comment was entered for this change.)</i>

**Blocking:** memcached-session-manager:145

**Comment by magro** [comment]
145 is now issue #187

**Comment by magro** [comment]
Superseded by upgrade to kryo 2/3, issue #270
