### ISSUE TITLE
tomcat shutdown Failed

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#238]
_From [gaetan.r...@gmail.com](https://code.google.com/u/103696725938500061447/) on February 25, 2014 16:52:32_

We've got an error  
The web application [/host-manager] appears to have started a thread named [Memcached IO over {MemcachedConnection to /172.27.0.242:11211} - SHUTTING DOWN (informed client)] but has failed to stop it. This is very likely to create a memory leak.

when shutdown Tomcat7

<b>What steps will reproduce the problem?</b>
1. configure msm&#13;
2. start tomcat&#13;
3. shutdown tomcat&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
good shutdown&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
msm-1.8.1  +tc7-1.8.1&#13;
tomcat 7&#13;
&#13;
our msm configuration&#13;
&lt;Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"&#13;
    memcachedNodes="&lt;CACHE_ENDPOINT&gt;"&#13;
    sticky="false"&#13;
    lockingMode="auto"&#13;
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"&#13;
    sessionBackupAsync="false"&#13;
    sessionBackupTimeout="100"&#13;
    /&gt;&#13;
&#13;
&#13;
thanks to solve this error

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=197_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 27, 2014 03:57:11_

msm obviously has asked the MemcachedClient to shutdown (see the thread name "SHUTTING DOWN (informed client)" and check the sources here: <a href="https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L2373" rel="nofollow">https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L2373</a>).&#13;
&#13;
Additionally I'd say tomcat logs a warning and you don't have a real application issue (of course it would be nice not to get this warning).&#13;
&#13;
What do you think is the issue in msm?

**Labels:** -Type-Defect Type-Other
