### ISSUE TITLE
request.getSession(false) delay 3 Seconds

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#248]
_From [hix...@gmail.com](https://code.google.com/u/111202749396891281793/) on May 29, 2014 05:42:08_

<b>What steps will reproduce the problem?</b>
1.one controller login success, create session and setAttribute(), then redirect to main page.&#13;
2. before enter main page, security interceptor check session, but session is null, wait 3 Seconds later, security check is ok.&#13;
3. when use tomcat7 standard session, everything is ok.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
memcached-session-manager 1.8.1 + tomcat7&#13;
&#13;

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=207_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 15, 2014 15:36:42_

Sounds like an issue with your infrastructure. Can you reproduce this with memcached running on localhost?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 15, 2014 15:39:01_

Sounds like you're using non-sticky sessions, are you using sessionBackupAsync="false"? (you should try this)
