### ISSUE TITLE
session expires in 30 minutes

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#250]
_From [zhouxiao...@gmail.com](https://code.google.com/u/106709041373097915706/) on July 08, 2014 11:03:56_

I expect session become expired when user has no operations in 30 minutes, but I can't find any attributes achiving this.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=209_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 08, 2014 02:42:25_

Please post the expected behaviour, the actual behavior, steps to reproduce the issue, and the msm configuration.
