### ISSUE TITLE
Null on non-sticky transient object.

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#259]
_From [shahinur...@gmail.com](https://code.google.com/u/117603931713862426778/) on November 23, 2014 08:29:37_

<b>What steps will reproduce the problem?</b>
1. Use some transient fields in JSF view scope bean.&#13;
2. Call another bean method using pram with that object from JSF.&#13;
3. The object instant is null as parameter.&#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
sticky is working fine so I am thinking non-sticky will also work but getting null object.&#13;
&#13;
<b>What version of the product are you using? On what operating system?</b>
&#13;
&#13;
<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=220_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 23, 2014 02:45:18_

I don't fully understand the issue (too little information), but I'd say that it's expected that transient fields are not initialized after deserialization. If you want that field to be (de)serialized then make it not transient.

**Comment by google-code-exporter** [comment]
_From [shahinur...@gmail.com](https://code.google.com/u/117603931713862426778/) on November 23, 2014 03:06:18_

Thanks for your response!

The scenario is, 
I have some transient properties in my controller which are bind with JSF page . My target is reduce CPU and IO usages. 
The things are working fine on following cases
1. If I don't configure "memcached-session-manager" with that application.
2. If I configure "memcached-session-manager" with sticky="true"

But when I am changing configurations from sticky="true" to sticky="false" then I am getting all of the transient variable / properties null in reference functions which is calling from JSF page. 

Could you please advise me in details, I am expecting similar behavior for sticky and non-sticky about transient variable.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 23, 2014 03:47:26_

On deserialization you need to initialize your transient variables. So it depends on the serialization strategy how to achieve this.

**Comment by google-code-exporter** [comment]
_From [shahinur...@gmail.com](https://code.google.com/u/117603931713862426778/) on November 23, 2014 09:55:21_

for your information I am initialize all of the transient variable in @-PostConstruct otherwise sticky session was not work perfectly.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on November 23, 2014 11:21:44_

As already said, you want to initialize your transient fields on deserialization. Assuming that you're using java serialization read the docs: <a href="https://docs.oracle.com/javase/6/docs/api/java/io/Serializable.html" rel="nofollow">https://docs.oracle.com/javase/6/docs/api/java/io/Serializable.html</a>
