### ISSUE TITLE
The second application "sess" cannot show the value setted by using the application "testSession" secondtime,it can only show the value setted by the first time. the session is is the same

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#269]
_From [guyi1...@gmail.com](https://code.google.com/u/108979706042488513059/) on September 23, 2014 10:43:12_

<b>What steps will reproduce the problem?</b>
1.Configuring the tomcat,set the sticky=true&#13;
2.Deploying two Applications:  testSessin.war  and  sess.war&#13;
3.Access the application testSession and set the key/value through the jsp page,for example key is 7 and value is 7&#13;
4  Access the application sess,i can see the key and value setted in the step 3，in other word,i can see the 7 in the jsp page.&#13;
&#13;
5. Access the appliction "testSession" again,  i add a set of key and value,for example i set the key and value the same is 9.  in this application's  jsp page  we can see two set of key and value,they are 7/7 and 9/9.&#13;
&#13;
6. Access the application "sess" again, but we can only sess the 7/7  in the jps page, the 9/9 cannot show. &#13;
&#13;
<b>What is the expected output? What do you see instead?</b>
&#13;
7/7 ,9/9&#13;
<b>What version of the product are you using? On what operating system?</b>
memcached-session-manager-1.6.0.jar&#13;
memcached-session-manager-tc6-1.6.0.jar&#13;
spymemcached-2.7.3.jar&#13;
&#13;
<b>Please provide any additional information below.</b>
&#13;
when i set the sticky=false, i can see the 7/7 and 9/9 in the jsp page of application  &#13;
"sess" ,  But when i set the sticy=true,i can only see the value setted by the application first time.  I also use telnet commond to sees the content in the session &#13;
stored in the memcached, the content is 7/7 an 9/9.  But why the 9/9 cannot show in the jsp page in the application.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=212_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 21, 2014 06:14:21_

Can you check if both session instances are the same (in terms of idprinting System.identityHashCode(session)?

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 21, 2014 06:19:44_

Can you also update msm to the latest version?

**Comment by magro** [comment]
Closed due to missing feedback.
