### ISSUE TITLE
Kryo 2/3 Support?

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#270]
_From [ja...@eatstreet.com](https://code.google.com/u/113363205409539957059/) on October 09, 2014 22:58:59_

I know that the custom serializers have been ready for a while. Is there any ETA for Kryo 2 or even 3 support in the session manager?

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=213_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 21, 2014 06:03:08_

I'm sorry, there's no ETA (too much work atm). We'd have to build upon the kryo pool and integrate a KryoFactory that allows to register custom Serializers. If you want to submit a pull request I'm happy to review /merge it :-)

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on June 19, 2015 15:46:11_

<i>(No comment was entered for this change.)</i>

**Status:** Started

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 21, 2015 15:46:25_

I finally managed to update msm-kryo-serializer to kryo2. It's not yet battle tested, I only checked that it's working with the simple sample project - therefore it's tagged as a release candidate (1.9.0-RC1).

See also the related announcement on the mailing list: <a href="https://groups.google.com/d/msg/memcached-session-manager/frIakVdjpV8/LqfrLNqVjTQJ" rel="nofollow">https://groups.google.com/d/msg/memcached-session-manager/frIakVdjpV8/LqfrLNqVjTQJ</a>&#13;
&#13;
I'll leave this issue open for some time...

**Comment by google-code-exporter** [comment]
_From [biggs.ja...@gmail.com](https://code.google.com/u/105066974250011984937/) on July 21, 2015 22:15:05_

I was actually just looking at this the other day. I might slip it in to one of our deploys and see how it handles. Awesome work!

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on July 21, 2015 23:41:28_

That would be great!

**Comment by nosideeffects** [comment]
Sorry it took so longer to reply. I have this up and running on our test servers right now, and nothing has gone awry. I will putting it into production next week to see how it fairs.

**Comment by magro** [comment]
No problem, thanks for the feedback! I'll close this issue now, problems should be reported as new issues.
