### ISSUE TITLE
【help】while I refresh the web page, the JsessionId is changing all the time

### ISSUE THREAD

**Issue by wenqibo** [magro/memcached-session-manager#274]
after I upgraded from 1.6... to 1.9... , while I refresh the web page, the JsessionId is changing all the time

log:

Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: >>>>>> Request starting: GET /login (requestedSessionId 60187B0CCACDF5173A7D90B799D36C71-n1.f1.tomcat8081) ==================
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id 'ping' and memcached id 'n1'.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.NodeAvailabilityCache updateIsNodeAvailable
FINE: CacheLoader returned node availability 'true' for node 'n1'.
2015-09-25 15:40:28,351 [DEBUG] com.huabid.web.filter.FlashScopeFilter.doFilterInternal(FlashScopeFilter.java:23)
========FlashScopeFilter.doFilterInternal()

Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Loading session from memcached: 60187B0CCACDF5173A7D90B799D36C71-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Session 60187B0CCACDF5173A7D90B799D36C71-n1.f1.tomcat8081 not found in memcached.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: createSession invoked: null
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id '3BACDB80EBE4F7BC5090CD47FB800010.f1.tomcat8081' and memcached id 'n1'.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: Created new session with id 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Skipping backup for session id 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081 as the session id is not usable for memcached.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=60187B0CCACDF5173A7D90B799D36C71-n1.f1.tomcat8081, version=0, secure=false
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081; Path=/; HttpOnly
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: <<<<<< Request finished: GET /login ==================
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: >>>>>> Request starting: GET /validateCode/get?1443166828548 (requestedSessionId 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081) ==================
2015-09-25 15:40:28,740 [DEBUG] com.huabid.web.filter.FlashScopeFilter.doFilterInternal(FlashScopeFilter.java:23)
========FlashScopeFilter.doFilterInternal()

Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Loading session from memcached: 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Session 3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081 not found in memcached.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: createSession invoked: null
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id '9ECD85B63EA3E4F78B1B0DC21DE4640D.f1.tomcat8081' and memcached id 'n1'.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: Created new session with id 9ECD85B63EA3E4F78B1B0DC21DE4640D-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id 9ECD85B63EA3E4F78B1B0DC21DE4640D-n1.f1.tomcat8081
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Skipping backup for session id 9ECD85B63EA3E4F78B1B0DC21DE4640D-n1.f1.tomcat8081 as the session id is not usable for memcached.
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=3BACDB80EBE4F7BC5090CD47FB800010-n1.f1.tomcat8081, version=0, secure=false
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=9ECD85B63EA3E4F78B1B0DC21DE4640D-n1.f1.tomcat8081; Path=/; HttpOnly
Sep 25, 2015 3:40:28 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: <<<<<< Request finished: GET /validateCode/get?1443166828548 ==================

**Comment by wenqibo** [comment]
Config:

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="n1:d98fa3b2a3b741b6.m.cnhzalicm10pub001.ocs.aliyuncs.com:11211"
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
    sticky="false"
    sessionBackupAsync="false"
    sessionBackupTimeout="100"
    memcachedProtocol="binary"
    transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
    copyCollectionsForSerialization="false"
    />


===========JARS=========
tomcat version: 7.0.64
tomcat lib :
memcached-session-manager-1.9.0-RC1.jar
memcached-session-manager-tc7-1.9.0-RC1.jar
spymemcached-2.11.1.jar

in my project with maven：
<dependency>
			<groupId>de.javakaffee.msm</groupId>
			<artifactId>msm-kryo-serializer</artifactId>
			<version>1.9.0-RC1</version>
		</dependency>

and  so on....please help me

**Comment by wenqibo** [comment]
and jdk version:1.7

**Comment by magro** [comment]
Can you test with 1.8.3 to see if this issue exists there?

**Comment by wenqibo** [comment]
change to 1.8.3， the issue still exists

log：


Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: >>>>>> Request starting: GET /login (requestedSessionId 6CB16F3EB0BFA0D7BF81EA1C33A27F79-n1.f1.tomcat8081) ==================
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id 'ping' and memcached id 'n1'.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.NodeAvailabilityCache updateIsNodeAvailable
FINE: CacheLoader returned node availability 'true' for node 'n1'.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Loading session from memcached: 6CB16F3EB0BFA0D7BF81EA1C33A27F79-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Session 6CB16F3EB0BFA0D7BF81EA1C33A27F79-n1.f1.tomcat8081 not found in memcached.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: createSession invoked: null
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id '3D8D593F20669352633D737126481610.f1.tomcat8081' and memcached id 'n1'.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: Created new session with id 3D8D593F20669352633D737126481610-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id 3D8D593F20669352633D737126481610-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Skipping backup for session id 3D8D593F20669352633D737126481610-n1.f1.tomcat8081 as the session id is not usable for memcached.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=6CB16F3EB0BFA0D7BF81EA1C33A27F79-n1.f1.tomcat8081, version=0, secure=false
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=3D8D593F20669352633D737126481610-n1.f1.tomcat8081; Path=/; HttpOnly
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: <<<<<< Request finished: GET /login ==================
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: >>>>>> Request starting: GET /validateCode/get?1443176547562 (requestedSessionId 3D8D593F20669352633D737126481610-n1.f1.tomcat8081) ==================
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Loading session from memcached: 3D8D593F20669352633D737126481610-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService loadFromMemcached
FINE: Session 3D8D593F20669352633D737126481610-n1.f1.tomcat8081 not found in memcached.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: createSession invoked: null
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.SessionIdFormat createSessionId
FINE: Creating new session id with orig id 'BE711D66888A852B587E70A1483375B4.f1.tomcat8081' and memcached id 'n1'.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.MemcachedSessionService createSession
FINE: Created new session with id BE711D66888A852B587E70A1483375B4-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id BE711D66888A852B587E70A1483375B4-n1.f1.tomcat8081
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Skipping backup for session id BE711D66888A852B587E70A1483375B4-n1.f1.tomcat8081 as the session id is not usable for memcached.
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugRequestSessionCookie
FINE: Have request session cookie: domain=null, maxAge=-1, path=null, value=3D8D593F20669352633D737126481610-n1.f1.tomcat8081, version=0, secure=false
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve logDebugResponseCookie
FINE: Request finished, with Set-Cookie header: JSESSIONID=BE711D66888A852B587E70A1483375B4-n1.f1.tomcat8081; Path=/; HttpOnly
Sep 25, 2015 6:22:27 PM de.javakaffee.web.msm.RequestTrackingHostValve invoke
FINE: <<<<<< Request finished: GET /validateCode/get?1443176547562 ==================

**Comment by wenqibo** [comment]
@magro

**Comment by magro** [comment]
After having a closer look at the logs the issue seems to be caused by the jvmRoute. Can you change it from f1.tomcat8081 to e.g. f1tomcat8081 (so that it does not contain a dot)?

**Comment by wenqibo** [comment]
Thanks,use 1.8.3 and  after change the jvmRoute, every thing is ok, thank u very much!

but the new issue is come when use 1.9.0RC1:

java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.MethodVisitor, but class was expected
	com.esotericsoftware.reflectasm.ConstructorAccess.insertConstructor(ConstructorAccess.java:124)
	com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:95)
	com.esotericsoftware.kryo.Kryo$DefaultInstantiatorStrategy.newInstantiatorOf(Kryo.java:1230)
	com.esotericsoftware.kryo.Kryo.newInstantiator(Kryo.java:1075)
	com.esotericsoftware.kryo.Kryo.newInstance(Kryo.java:1084)
	com.esotericsoftware.kryo.serializers.MapSerializer.create(MapSerializer.java:120)
	com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:124)
	com.esotericsoftware.kryo.serializers.MapSerializer.read(MapSerializer.java:39)
	com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:683)
	de.javakaffee.web.msm.serializer.kryo.KryoTranscoder.deserializeAttributes(KryoTranscoder.java:210)
	de.javakaffee.web.msm.TranscoderService.deserializeAttributes(TranscoderService.java:171)
	de.javakaffee.web.msm.TranscoderService.deserialize(TranscoderService.java:128)
	de.javakaffee.web.msm.MemcachedSessionService.loadFromMemcached(MemcachedSessionService.java:1100)
	de.javakaffee.web.msm.MemcachedSessionService.findSession(MemcachedSessionService.java:585)
	de.javakaffee.web.msm.MemcachedBackupSessionManager.findSession(MemcachedBackupSessionManager.java:216)
	org.apache.catalina.connector.Request.doGetSession(Request.java:2995)
	org.apache.catalina.connector.Request.getSession(Request.java:2385)
	org.apache.catalina.connector.RequestFacade.getSession(RequestFacade.java:897)
	com.huabid.web.filter.FlashScopeFilter.doFilterInternal(FlashScopeFilter.java:24)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
note The full stack trace of the root cause is available in the Apache Tomcat/7.0.64 logs.



so。。。。now，
i change the transcoderFactoryClass from 
de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory
to
de.javakaffee.web.msm.serializer.javolution.JavolutionTranscoderFactory

and every thing is ok。。。but i still not understand why can not use kryo。。。

kevin li
thanks

**Comment by magro** [comment]
Great that it's working with the changed jvmRoute! 

When switching back to 1.9.0RC1 did you also change your application back to msm-kryo-serializer 1.9.0RC1, as well as msm in tomcat? IIRC I tested msm samples in 1.9.0RC1 with kryo and didn't encounter this issue.

**Comment by wenqibo** [comment]
yes, i change my application back to kryo in pom.xml, and replace jars in tomcat lib path. but  the issue still exists.

like this:

![1ce292d3-8a6c-4a5f-9df0-6f1e3e71f1f6](https://cloud.githubusercontent.com/assets/4066180/10115816/13f2b63a-644a-11e5-92ef-ab74bccc2ecb.png)
![6d8d6c5e-eed1-40c2-94e8-5ecec36049ae](https://cloud.githubusercontent.com/assets/4066180/10115817/1422258c-644a-11e5-9359-c58d0bfe263d.png)
![53a82c7c-4643-425f-82d3-2412a9dfd1d1](https://cloud.githubusercontent.com/assets/4066180/10115818/14239084-644a-11e5-9d55-0ac98145fe2e.png)
![e11b2967-6de5-4551-98ba-7b9003711d3a](https://cloud.githubusercontent.com/assets/4066180/10115860/8c19035c-644b-11e5-84c4-c569731145dc.png)

**Comment by magro** [comment]
Ok. Because the originally reported issue is resolved we can close this
one. For the newly encountered issue it would be nice if you could submit
another issue, I'll have a look at it the next days.
Am 26.09.2015 06:39 schrieb "wenqibo" <notifications@github.com>:

**Comment by wenqibo** [comment]
Ok,thanks Martin。
