### ISSUE TITLE
Not able to build for tomcat7

### ISSUE THREAD

**Issue by bhaktirajdev** [magro/memcached-session-manager#277]
On mvn package I get this error:

Failed to execute goal on project memcached-session-manager-tc7: Could not resolve dependencies for project de.javakaffee.msm:memcached-session-manager-tc7:jar:1.9.0-RC2-SNAPSHOT: The following artifacts could not be resolved: de.javakaffee.msm:memcached-session-manager:jar:1.9.0-RC2-SNAPSHOT, de.javakaffee.msm:memcached-session-manager:jar:tests:1.9.0-RC2-SNAPSHOT: Failure to find de.javakaffee.msm:memcached-session-manager:jar:1.9.0-RC2-SNAPSHOT in https://oss.sonatype.org/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-releases has elapsed or updates are forced -> [Help 1]

**Comment by magro** [comment]
Does an mvn install in the top project work for you? The core module needs to be mvn installed before building dependent modules.

**Comment by bhaktirajdev** [comment]
Yes it worked. Thank you.! :)
