### ISSUE TITLE
When session is expired when memcache-session-manager is used?

### ISSUE THREAD

**Issue by XiaokunHou** [magro/memcached-session-manager#278]
I am new user of this tool. If session timeout is set in application level, the memcache will store session in the same time period? Or it will store session as long as 30 days?

Thanks.

**Comment by XiaokunHou** [comment]
How memcache-session-manager expire session for non-sticky  and sticky sessions?

**Comment by magro** [comment]
First: please use the mailing list for questions. 

msm stores them in memcached with the session timeout. Each session access updates the session timeout in memcached. There are a few optimizations to this, but that's basically how it works.
When the application invalidates a session, msm removed it from memcached. 

HTH.
