### ISSUE TITLE
New session on tomcat failover

### ISSUE THREAD

**Issue by wellwininfotech** [magro/memcached-session-manager#281]
I have set MSM with below config

<Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="n1:localhost:11211,n2:localhost:12345"
    sticky="true"
    sessionBackupAsync="true"
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
    transcoderFactoryClass="de.javakaffee.web.msm.JavaSerializationTranscoderFactory" />

In production we have two tomcat nodes behing the haproxy.  We run the script which put the tomcat in maintenance and then restart tomcat and put it back to pool. We run this script on each tomcat for every hour at different time. 

Now on tomcat restart, some time, request gets to other node and it creates new session with all existing session attributes. (I am not sure how and why, its does not happen every time also.)

This is causing major issue as same session have few old attributes and few new attributes. (On new session creation we add few attribute to session)

Need your help in resolving this.

**Comment by wellwininfotech** [comment]
Update on this.
On debugging I found that when same session request is served by different tomcat, Query to memcache is returning session with isNew=true, which is causing the issue.

Ideally session stored in memcache could never to new.

**Comment by magro** [comment]
@wellwininfotech Sorry for the late response, is this still an issue for you?

**Comment by wellwininfotech** [comment]
@magro 

I made change in my application code. Issue is resolved.

**Comment by magro** [comment]
@wellwininfotech great you solved it! Can you tell what you've changed to fix it?
