### ISSUE TITLE
 Session Attributes are Lost After Node Switch

### ISSUE THREAD

**Issue by RemyaPR** [magro/memcached-session-manager#282]
We have recently integrated MemcachedBackupSessionManager with our application and we see one issue that session attributes are not retrieved successfully after a node switch but the behavior is not consistent.

We have a target to promote this to staging environment by next week. 
Requesting your support at the earliest on this case which will be really helpful for us to pass the customer testing in the staging environment.

<h6>Our Application:  </h6>
Flight Search Engine listing products based on search criterion like origin, destination etc.

<h6>Environment:</h6> two Tomcat 6.0.24  nodes (say tc1,tc2) balanced by a sticky apache load balancer
<h6>Context XML config:</h6>                     
Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"   memcachedNodes="http://192.168.185.168:8091/pools
memcachedProtocol="binary" 
operationTimeout="10000"  
sessionAttributeFilter="^(?!.*fareCatalogHandlerMap).*$" 
requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$" username="SessionBucket"

<h6> What steps will reproduce the problem?</h6>
1. Perform a search in tc2 (node2)
2. BEFORE COMPLETION OF SEARCH in tc2 , disconnect tc2 from load balancer
3. Next action from the page will hit  tc1 but lead to session expiry due missing session attributes in tc1 ( please find the logs from tc1 attached)

[catalina_tc1.txt](https://github.com/magro/memcached-session-manager/files/75364/catalina_tc1.txt)

Note : The issue will not happen if tc2 is disconnected AFTER COMPLETION OF SEARCH(Step2 above)

<h6>What is the expected output? What do you see instead?</h6>
session attributes should be retrieved correctly in tc2

**Comment by magro** [comment]
If step 1 (Perform a search in tc2) is the first request (new session) and
tc2 is shut down before the request is finished it's expected that this
session is not available in memcached because the session is pushed to
memcached at the end of the request.

What happens if the session is created before step 1?

Can you share logs for step 1, 2 and 3 (e.g. on pastebin) with debug
logging enabled?

Cheers,
Martin
Am 31.12.2015 06:02 schrieb "RemyaPR" <notifications@github.com>:

**Comment by magro** [comment]
If for such long running requests you definitely need to push a session to
memcached before the request is finished we might find a way that allows
you to hook into this process. Is this what you're looking for?
Am 31.12.2015 10:13 schrieb "Martin Grotzke" <martin.grotzke@googlemail.com

**Comment by RemyaPR** [comment]
Sorry that the steps we mentioned are not in detail. 

We have a login transaction before the flight search. After login, we have tested session replication and found that Username and other details are stored to session and replicated correctly. 

After login, user can perform the flight search. And if the node switch happens during this search, the login details (which were there in session as part of previous login transaction) are not getting retrieved in second node after the node switch. 

The problem here is that all the session attributes including the previous transaction data are lost. 
And this is also occasionally.

**Comment by RemyaPR** [comment]
One more information... in the logs of the second node, we could see the session attributes getting deserialized, but finally we are not getting the attributes in the application code. We suspect somewhere in between it is lost...Could you please check the logs attached in the first issue comment - catalina_tc1.txt

*Dec 21, 2015 8:24:19 PM de.javakaffee.web.msm.JavaSerializationTranscoder deserializeAttributes
FINE:   loading attribute 'ehnCode' with value 'TYO'
Dec 21, 2015 8:24:19 PM de.javakaffee.web.msm.JavaSerializationTranscoder deserializeAttributes
FINE:   loading attribute 'displayID' with value 'FBTS02'*

**Comment by magro** [comment]
I see two requests that probably shouldn't need/cause the session to be
loaded:

FINE: >>>>>> Request starting: GET
/fb/js/jquery.dotdotdot-1.2.1.js?version=HIS_EXT_PH3.1.67.0

FINE: >>>>>> Request starting: GET
/fb/store/shop/getIcon.htm?iconType=PEX_FARE_STOREAGENT

Please change the requestUriIgnorePattern so that these requests are
matched by this pattern as well.

Perhaps they are the reason for the occasional failures.

Cheers,
Martin
Am 31.12.2015 10:43 schrieb "RemyaPR" <notifications@github.com>:

**Comment by magro** [comment]
To have more consistent results please set sessionBackupAsync=false.

**Comment by magro** [comment]
Related issues: #257 and #280

**Comment by RemyaPR** [comment]
Hi @magro,

Thank you for the response.

After implementing sessionBackupAsync =false and modifying the url pattern the frequency of the issue occurrence reduced but still the issue occur at times. The issue occurs when parallel Ajax requests are issued by system.
 **Trace**
=== Ajax Request 1 ======*(deleteFromMemcached called, The final datalength is  34302)*

FINE: >>>>>> Request starting: GET /fb/store/shop/getWishListFromCache.htm (requestedSessionId D2813BD9D54934FDBEA7BA403BB05C42.node1) ==================
Jan 6, 2016 2:14:12 PM de.javakaffee.web.msm.MemcachedSessionService deleteFromMemcached
FINE: Deleting session from memcached: D2813BD9D54934FDBEA7BA403BB05C42.node1
Jan 6, 2016 2:14:12 PM de.javakaffee.web.msm.BackupSessionService backupSession
FINE: Starting for session id D2813BD9D54934FDBEA7BA403BB05C42.node2
Jan 6, 2016 2:14:12 PM de.javakaffee.web.msm.BackupSessionTask call
FINE: Starting for session id D2813BD9D54934FDBEA7BA403BB05C42.node2
...
Jan 6, 2016 2:14:13 PM net.spy.memcached.protocol.TCPMemcachedNodeImpl transitionWriteItem
FINE: Finished writing Cmd: 1 Opaque: 169 Key: D2813BD9D54934FDBEA7BA403BB05C42.node2 Cas: 0 Exp: 3594 Flags: 2050 Data Length: 34302
 
=== Ajax Request 2 ======*(deleteFromMemcached called, The final datalength is  171)*

FINE: >>>>>> Request starting: GET /fb/store/shop/getSortOption.htm (requestedSessionId D2813BD9D54934FDBEA7BA403BB05C42.node1) ==================
Jan 6, 2016 2:14:13 PM de.javakaffee.web.msm.MemcachedSessionService deleteFromMemcached
FINE: Deleting session from memcached: D2813BD9D54934FDBEA7BA403BB05C42.node1
...
Jan 6, 2016 2:14:13 PM net.spy.memcached.protocol.TCPMemcachedNodeImpl transitionWriteItem
FINE: Finished writing Cmd: 1 Opaque: 171 Key: D2813BD9D54934FDBEA7BA403BB05C42.node2 Cas: 0 Exp: 3594 Flags: 2048 Data Length: 171
 
When the  second ajax request hits node2, the session attributes written are lost.Full Logs is attached for your reference .
 
[log_issue.txt](https://github.com/magro/memcached-session-manager/files/81866/log_issue.txt)

Could you please share some solution or workaround.

**Comment by magro** [comment]
Great analysis! I think I found the race condition in the code and hopefully fixed it in master. Can you build from master, run mvn install and try the new jars?

**Comment by magro** [comment]
I also just built the jars, unfortunately github doesn't allow to upload jars. You can find them here:
https://www.dropbox.com/s/igv0p47vccc0r05/memcached-session-manager-1.9.0-RC2-SNAPSHOT.jar?dl=0
https://www.dropbox.com/s/z0ezcpqumoqik2y/memcached-session-manager-tc6-1.9.0-RC2-SNAPSHOT.jar?dl=0

**Comment by RemyaPR** [comment]
Hi @magro,
Thank you for the update. We are doing the testing with the new jars. Will update you the results soon.

In between, with the new jars can we use the configuration sessionBackupAsync=true ?
Do you foresee some issues with new jars in 'sessionBackupAsync=true' mode ?

**Comment by magro** [comment]
I consider sessionBackupAsync=true an optimization for cases where you
value better performance in the common case more than unreliable results in
failure situations. And I regret that I chose sessionBackupAsync=true as
default. So I'd suggest you keep sessionBackupAsync=false until you're sure
that this works. Then you can decide and test how sessionBackupAsync=true
works for you.
Am 12.01.2016 11:53 schrieb "RemyaPR" <notifications@github.com>:

**Comment by RemyaPR** [comment]
Hi @magro,

We had a good round of testing, and the issue has not been repeated after your fix. Thank you very much for the wonderful support!!

**Comment by magro** [comment]
Released with 1.9.1.
