### ISSUE TITLE
Possible issue with Tomcat 7.0.68

### ISSUE THREAD

**Issue by kimmob** [magro/memcached-session-manager#287]
We got major issues upgrading from 7.0.67 to 7.0.68. The sessions gets invalidated after around 30 seconds. We do use an old version of the manager so I do not know for sure there is a problem with the latest version.

Using:
x memcached-session-manager-1.6.3.jar
x memcached-session-manager-tc7-1.6.3.jar
x spymemcached-2.8.4.jar

Sorry for reporting a problem with an ancient version, I just thought it could be interesting to investigate the changes in .68.

**Comment by magro** [comment]
Can you do me a favor and check the sample https://github.com/magro/memcached-session-manager/tree/master/samples with 68? The tomcat version is a property in the pom.

**Comment by kimmob** [comment]
Sure. Changed to but it to '<tomcat-version>7.0.68</tomcat-version>' still starts with:
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47

How can we test if session-timeout have dropped significant after i get the test running? I can look in the memcached console-log perhaps.

**Comment by kimmob** [comment]
Needs to change version in some other way.

http://stackoverflow.com/questions/29155637/tomcat-7-maven-plugin-running-differrent-version-of-tomcat

**Comment by magro** [comment]
Ok, this is in master now, with .68. When running the sample, http://localhost:9090/counter shows a lower session timeout compared to 67. Strange, maybe it's a bug in tomcat?

**Comment by kimmob** [comment]
Maybe I found a bug after all. Why do I always have to be the first one :)

**Comment by magro** [comment]
Can you reproduce this issue with plain tomcat and no msm involved?

**Comment by kimmob** [comment]
What I did was removing:

  <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="n1:XXXXX:11211"
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
    sticky="false"
     />

from context.xml. But of course got stuck to just using one single node instead of the cluster.

And everything started to work as expected. But I haven't tried with any other session-manager.

**Comment by magro** [comment]
When you removed the Manager element you actually used the StandardManager. If it worked as expected in this configuration, what is what I understand from your message, it seems to be an issue with msm.
Not sure what's going on here. If you'd like to further investigate/debug, this would be great!

**Comment by kimmob** [comment]
You understood it correct, it worked with StandardManager, I will try to look into it.

**Comment by magro** [comment]
@kimmob The latest tomcat 6.0.45 seems to have a similar issue, just FYI.

**Comment by magro** [comment]
@kimmob I just released 1.9.2 with the fix.
