### ISSUE TITLE
Closing a Couchbase Bucket

### ISSUE THREAD

**Issue by rajumtmm123** [magro/memcached-session-manager#292]
HI magro,

We have recently implemented data caching using couch-base in-memory. we have configured few buckets (couch-base bucket) for storing our application data objects in to in-memory db cache. Is it required to close these couch-base Buckets in the application in any situation. will couchbase internally handle closing these buckets during idle time?

Requesting your support at the earliest .

Thanks
Raju A

**Comment by magro** [comment]
You should ask this the couchbase guys.
