### ISSUE TITLE
Monitoring sessions count

### ISSUE THREAD

**Issue by JakubDziworski** [magro/memcached-session-manager#299]
I am using non sticky configuration:

```
 <Manager className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="n1:host1.yourdomain.com:11211,n2:host2.yourdomain.com:11211"
    sticky="false"
    sessionBackupAsync="false"
    lockingMode="auto"
    transcoderFactoryClass="de.javakaffee.web.msm.serializer.kryo.KryoTranscoderFactory"
    />
```

The sessions are sucesfully stored and retrieved from memcache nodes. 

There is however problem with getting sessions count. In tomcat manager the value is 0. I also have a code that retrieves sessions count manually:

```java
MBeanServer mBeanServer = ManagementFactory.getPlatformMBeanServer();
String contextPath = request.getServletContext().getContextPath();
ObjectName objectName = new ObjectName("Catalina:type=Manager,context="+contextPath+",host=localhost");
Object activeSessions = mBeanServer.getAttribute(objectName, "activeSessions");
return (Integer) activeSessions; 
```

Before adding memcache session manager it always returned correct value. Now It always returns values from 0 to 3.

It seems like an session is stored in the local tomcat and immadietaly freed after it has been sent to memcache. I thought that was the case but then I read the wiki where it says:

> The memcached session manager installed in a tomcat holds all sessions locally in the own jvm, just like the StandardManager does it as well.

**Are non-sticky sessions stored locally?**. If that is the case how can I **get sessions count**?

**Comment by magro** [comment]
This paragraph in the docs also say  "needs to be updated for non-sticky sessions" ;-) I just updated it a bit, but it needs to be described in greater detail. In short you're right, for non-sticky sessions the session manager removes a session from its local session map at the end of a request (to prevent stale session state).

The question regarding session count for non-sticky sessions has been asked on the mailing list before (perhaps also submitted as an issue, not sure), please check what has already been discussed.
