### ISSUE TITLE
Session Invalidated with AppCookieStickinessPolicy

### ISSUE THREAD

**Issue by dhafley** [magro/memcached-session-manager#317]
We are able to make this work with LBCookieStickinessPolicy but not with JSESSIONID.  Are there additional configuration options that should be supplied for JSESSIONID?  What tips do you have to debug JSESSIONID session stickiness?

**Comment by magro** [comment]
Sounds like an AWS specific question, sorry to say that I can't help there. You could ask on the mailing list, hopefully other AWS users can step in. You should describe the actual issue you have a bit more detailed (what exactly does not work).

**Comment by dhafley** [comment]
Thanks for the quick reply.  In testing our deployment is pretty simple, we have two nodes connected to an ElastiCache cluster that has one node.  When setup with sticky session based on JSESSIONID, I'm immediately logged out when the application server I'm stuck to goes out of rotation.  I've managed to keep an active session most of the time (4/5 times when pulling server in/ out of rotation) when disabling connection draining and using LBCookieStickinessPolicy.  

The inconsistency is the main problem and I'm wondering if any of the timeout options or async would be recommended.  

I don't believe that is any problem with the project, mostly looking for direction and information.  I'll also reach out to AWS support and see what feedback they can provide. 

Thanks again for this project.

**Comment by magro** [comment]
Not sure what your configuration looks like, of course I'd recommend to use sessionBackupAsync=false. Can you reproduce the issue with a simple load balanced tomcat setup?

**Comment by magro** [comment]
Is this still an issue?
