### ISSUE TITLE
Kryo Builder Configuration does not work

### ISSUE THREAD

**Issue by JamieGHamilton** [magro/memcached-session-manager#321]
I created a custom version of de.javakaffee.web.msm.serializer.kryo.KryoBuilderConfiguration with no luck in setting the class resolver.  The first problem I see is that the return value of configure(KryoBuilder kryoBuilder) is ignored.  Hard to see how the included builder configurations would work (like de.javakaffee.web.msm.serializer.kryo.WicketSerializerFactory).  Another thing I see is that the "withX(.." methods in the KryoBuilder class that call buildFrom(KryoBuilder.this) - this method has no effect since "KryoBuilder.this" is the same as "this" (I checked it in the debugger)

**Comment by magro** [comment]
@JamieGHamilton Thanks for bringing this up!

> I created a custom version of de.javakaffee.web.msm.serializer.kryo.KryoBuilderConfiguration with no luck in setting the class resolver. The first problem I see is that the return value of configure(KryoBuilder kryoBuilder) is ignored.

In #328 I've fixed the issue with the ignored `config.configure` return value.

> Hard to see how the included builder configurations would work (like de.javakaffee.web.msm.serializer.kryo.WicketSerializerFactory)

I agree that the builder related things are not that straight forward - if you've any suggestions how this could be improved I'd be happy to hear them!

> Another thing I see is that the "withX(.." methods in the KryoBuilder class that call buildFrom(KryoBuilder.this) - this method has no effect since "KryoBuilder.this" is the same as "this" (I checked it in the debugger)

I don't see the issue here. In #328 I've added a test that shows that `KryoBuilder` works as expected. Maybe you can provide a concrete case (test) that shows what's not working as expected?

**Comment by JamieGHamilton** [comment]
Hi magro, thanks for looking into this. I tried your unit test and it succeeds but the order of calls is dependent.  For example, I moved the first withKryoCustomization call to the top and builder no longer sets the class resolver, reference resolver or stream factory.
		Kryo kryo = kryoBuilder 
				.withKryoCustomization(enableAsm) 
				.withClassResolver(classResolver) 
				.withReferenceResolver(referenceResolver) 
				.withStreamFactory(streamFactory) 
				.withInstantiatorStrategy(instantiatorStrategy) 
				.withRegistrationRequired(true) // Kryo default is false 
				.withReferences(false) // Kryo default is true 
				.withKryoCustomization(registerMyCollectionSerializer) 
				.build();

**Comment by JamieGHamilton** [comment]
I have a suggested fix: Change
private Kryo buildFrom(KryoBuilder target) {
to
protected Kryo buildFrom(KryoBuilderJ target) {
and
change 
Kryo k = buildFrom(KryoBuilder.this);
to
Kryo k = this.buildFrom(KryoBuilder.this);
in the 4 methods it's called.

**Comment by magro** [comment]
@JamieGHamilton thanks for catching this, I've fixed the code according to your suggestion.

**Comment by JamieGHamilton** [comment]
thanks magro!!!

**Comment by magro** [comment]
Btw, I released it yesterday as 2.1.0

**Comment by JamieGHamilton** [comment]
Hi again magro, unfortunately I have found another problem with the customization.  The class resolver that I provide inherits from com.esotericsoftware.kryo.util.DefaultClassResolver which holds a state (some maps) and needs to be a new instance per new Kryo object.  The customization only creates one kyro builder for the kryo factory and so all new Kryo objects share the same class resolver that you provide. (This would be a problem for someone using de.javakaffee.web.msm.serializer.kryo.CGLibProxySerializerFactory as well because the class resolver is overriden).  My suggested fix would be to create a new kryo builder for each new kryo to prevent this from happening.  You could change:
    private KryoFactory createKryoFactory(final ClassLoader classLoader,
                                          final String[] customConverterClassNames,
                                          final boolean copyCollectionsForSerialization) {

        KryoBuilder kryoBuilder = new KryoBuilder() {
            @Override
            protected Kryo createKryo(ClassResolver classResolver, ReferenceResolver referenceResolver, StreamFactory streamFactory) {
                return KryoTranscoder.this.createKryo(classResolver, referenceResolver, streamFactory,
                        classLoader, customConverterClassNames, copyCollectionsForSerialization);
            }
        }.withInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

        final List<KryoBuilderConfiguration> builderConfigs = load(KryoBuilderConfiguration.class, customConverterClassNames, classLoader);
        for(KryoBuilderConfiguration config : builderConfigs) {
            kryoBuilder = config.configure(kryoBuilder);
        }

        final KryoBuilder finalKryoBuilder = kryoBuilder;
        return new KryoFactory() {
            @Override
            public Kryo create() {
                Kryo kryo = finalKryoBuilder.build();
TO:
    private KryoFactory createKryoFactory(final ClassLoader classLoader,
                                          final String[] customConverterClassNames,
                                          final boolean copyCollectionsForSerialization) {

        return new KryoFactory() {
            @Override
            public Kryo create() {
                KryoBuilder kryoBuilder = new KryoBuilder() {
                    @Override
                    protected Kryo createKryo(ClassResolver classResolver, ReferenceResolver referenceResolver, StreamFactory streamFactory) {
                        return KryoTranscoderJ.this.createKryo(classResolver, referenceResolver, streamFactory,
                                classLoader, customConverterClassNames, copyCollectionsForSerialization);
                    }
                }.withInstantiatorStrategy(new Kryo.DefaultInstantiatorStrategy(new StdInstantiatorStrategy()));

                final List<KryoBuilderConfiguration> builderConfigs = load(KryoBuilderConfiguration.class, customConverterClassNames, classLoader);
                for(KryoBuilderConfiguration config : builderConfigs) {
                    kryoBuilder = config.configure(kryoBuilder);
                }

            	Kryo kryo = kryoBuilder.build();

**Comment by magro** [comment]
Ok, can you submit a PR?

**Comment by JamieGHamilton** [comment]
Fixed with #330
