### ISSUE TITLE
The class concurrentHashMap is not supported

### ISSUE THREAD

**Issue by LiuYanLL** [magro/memcached-session-manager#332]
A problem happend if i put a concurrentHashMap into session ,when i get it from session it becomes a hashMap.Could you give me some suggestion?thanks very much.

the jar's version i used  is,
flexjson-3.3.jar   
spymemcached-2.11.1.jar  
msm-flexjson-serializer-1.8.3.jar 
memcached-session-manager-tc8-1.8.0.jar 
memcached-session-manager-1.8.0.jar

**Comment by magro** [comment]
I've never used the flexjson serializer myself, it was contributed by a user. I guess one needs to configure the related deserializer differently. Of course you can submit a pull request, or you just (somehow) configure the deserializer customized for your needs without any change in msm.

**Comment by LiuYanLL** [comment]
Thanks for your reply.
Maybe the reason is that object is serialized by flexjson as a json String,so it could not be converted back.Finally i choose kryo serializer in msm, the issue is resolved.
