### ISSUE TITLE
How to configure multiple connections to a couchbase cluster? 

### ISSUE THREAD

**Issue by pietervogelaar** [magro/memcached-session-manager#340]
Do I have to use moxi or is it also possible to configure in msm?

What is recommended?

**Comment by pietervogelaar** [comment]
Any update on this?

**Comment by magro** [comment]
One question would be what you're going to achieve. Failover, Loadbalancing? AFAIK/IIRC the couchbase client already provides failover, but I could be wrong so you should check the current state and exact properties of the client.

**Comment by pietervogelaar** [comment]
To achieve failover when one couchbase server goes down. Can I specify multiple nodes in the memcachedNodes property? Or does the :8091/pools already exposes all the cluster nodes?

**Comment by pietervogelaar** [comment]
Ah I found an example here https://github.com/magro/memcached-session-manager/issues/291. The property can take multiple hosts I see.

**Comment by magro** [comment]
Correct, great that you found it! :-)
So can we close this issue?

**Comment by pietervogelaar** [comment]
Yes this issue can be closed, thanks!
