### ISSUE TITLE
Session Timeouts on Tomcat 7.0.68/Ubuntu 16.04

### ISSUE THREAD

**Issue by scott-wood-vgh** [magro/memcached-session-manager#341]
We have been using MSM on our Ubuntu 14.04/Tomcat 7.0.52 for some time. Recently, we decided to upgrade to Ubuntu 16.04/Tomcat 7.0.68, and started experiencing abnormal session timeouts. Our app's web.xml specifies a session timeout of 180 (3 hours) but customers started experiencing timeouts of around 30 minutes. 

I found this issue: https://github.com/magro/memcached-session-manager/issues/287 but we were already using the 1.9.2 release. Do I have to set a timeout in context.xml consistent with the 180 minutes in the app's web.xml to ensure sessions don't time out early? Below is my current context.xml:

<?xml version='1.0' encoding='utf-8'?>

<Context>

    
    <WatchedResource>WEB-INF/web.xml</WatchedResource>

    <Manager
    className="de.javakaffee.web.msm.MemcachedBackupSessionManager"
    memcachedNodes="my-elasticache.ffvmii.cfg.use1.cache.amazonaws.com:11211"
    requestUriIgnorePattern=".*\.(ico|png|gif|jpg|css|js)$"
    sessionBackupAsync="true"
    sticky="true"
    copyCollectionsForSerialization="false"
    />

</Context>

Any help would be greatly appreciated!

**Comment by magro** [comment]
As you can see in #287 after 1.9.2 there was added commit 2befaa5 which fixed a bug that sounds related to what you're reporting, and which was released with 1.9.6. Can you test with 1.9.6 or later?

**Comment by scott-wood-vgh** [comment]
Thanks for your reply! I upgraded to 1.9.6 but I am still seeing the issue after restarting the Tomcat service. I also added 

maxInactiveInterval="10800"

to my context.xml (3 hours). Was this the correct place to set it? If so, should I evict any sessions/flush Memcached to see a change?

**Comment by magro** [comment]
Session lifetime is determined on creation, so please test with a new session (just clear cookies). To configure the session timeout please use mechanisms according to tomcat docs (to be honest I'm not sure about maxInactiveInterval in context.xml), a usual thing is to configure the sessionTimeout in web.xml.
