### ISSUE TITLE
Documentation missing dependency for Kryo

### ISSUE THREAD

**Issue by papersackpuppet** [magro/memcached-session-manager#345]
The Kryo serializer now requires the objenesis library from [objenesis.org](objenesis.org) or [mvnrepository](https://mvnrepository.com/artifact/org.objenesis/objenesis) but it is not mentioned in [Add custom serializers to your webapp](https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration#add-custom-serializers-to-your-webapp-optional).

[See here for more info](https://github.com/EsotericSoftware/kryo#using-kryo-without-maven)

**Comment by wenfanchao** [comment]
That's right, it's a very big mistake

**Comment by magro** [comment]
Thanks for reporting! You can also improve the wiki, has been done in the meanwhile.
