### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by cdx-grillo** [magro/memcached-session-manager#361]
I'm not able to run **mvn clean test**, there's a problem with the couchbase version/maven repo (error shown below).   I've played around with changing the couchbase version and various other pom settings but can't seem to get it to work, any ideas? 

[ERROR] Failed to execute goal on project memcached-session-manager: Could not resolve dependencies for project de.javakaffee.msm:memcached-session-manager:jar:2.1.2-SNAPSHOT: Failure to find org.couchbase.mock:CouchbaseMock:jar:0.5-69e953bd in https://oss.sonatype.org/content/repositories/releases was cached in the local repository

**Comment by tjennings** [comment]
Hey!  We ran into this same problem.  As a workaround,  you can download the jar manually here: 

https://github.com/xulunfan/memcached-session-manager/tree/master/maven/org/couchbase/mock/CouchbaseMock/0.5-69e953bd

then run this command to install it locally: 

mvn install:install-file -Dfile=CouchbaseMock-0.5-69e953bd.jar -DgroupId=org.couchbase.mock -DartifactId=CouchbaseMock -Dversion=0.5-69e953bd -Dpackaging=jar

**Comment by mikeebert** [comment]
Note, when downloading the jar be sure to use the 'download link' [on this page](https://github.com/xulunfan/memcached-session-manager/blob/master/maven/org/couchbase/mock/CouchbaseMock/0.5-69e953bd/CouchbaseMock-0.5-69e953bd.jar)

**Comment by magro** [comment]
Have you tried upgrading the version in pom.xml, according to https://mvnrepository.com/artifact/com.couchbase.mock/CouchbaseMock?
