### ISSUE TITLE
when I open a web page(contains static file request) it generated different session ids

### ISSUE THREAD

**Issue by wangfeng1988** [magro/memcached-session-manager#371]
@magro
when I open a web page(contains static file request) it generated different session ids. so when I login this website, I missed the session sometimes.
environment: jdk1.7, tomcat-8.0.47, msm2.1.1, spymemcached-2.12.3, JavaSerialization
my tomcat conf:
![33333](https://user-images.githubusercontent.com/4754449/33237063-52934214-d2a3-11e7-8532-5fea68d5d9be.png)

here is the log:
![image](https://user-images.githubusercontent.com/4754449/33237015-c4497d58-d2a1-11e7-8626-3098a0fbd8ef.png)

**Comment by wangfeng1988** [comment]
It is so interesting that when I set requestUriIgnorePattern= ".*\.(ico|png|gif|jpg|css|js)\?m.*" , It is working well. I don't know why. Look forward to your reply. Thanks.

**Comment by magro** [comment]
@wangfeng1988 sorry for the late response, and unfortunately I cannot explain your observations. Is this still relevant, or can we close this issue?
