### ISSUE TITLE
tomcat 8.5.31 has session timeout with memcached jars

### ISSUE THREAD

**Issue by beeramcse** [magro/memcached-session-manager#381]
hi ,

tomcat 8.5.31 has session timeout with memcached jars

below are msm jars
memcached-session-manager-tc8-2.1.1
memcached-session-manager-2.1.1
spymemcached-2.12.0

**Comment by afarentino** [comment]
Are you seeing this behavior on earlier minor releases of tomcat 8.5 as well? Any info you can share on your config of the session manager would be helpful as well. We are currently experiencing some trouble migrating a tomcat 8.0 cluster using non sticky sessions to using 8.5 4 and are wondering if the issue you found is related. Thanks!

**Comment by magro** [comment]
More info is needed for being able to help. Please reopen if help is still needed.
