### ISSUE TITLE
Wiki home needs an update

### ISSUE THREAD

**Issue by ballapete** [magro/memcached-session-manager#383]
Hello!

Wiki home,https://github.com/magro/memcached-session-manager/wiki, states that only Tomcats 6, 7, and 8 are supported. The much younger page https://github.com/magro/memcached-session-manager/wiki/SetupAndConfiguration adds Tomcat 9 to the list of supported versions.

Which information is true?

--

Greetings

    Pete

**Comment by magro** [comment]
Thanks for pointing that out! Tomcat 9 is supported, I updated the wiki entry page.
