### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#56]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 17, 2009 23:41:53_

For 1.0 there must be basic documentation: how to install and configure
this session manager.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=12_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 12, 2009 08:49:11_

Things to cover:
- meaning of failoverNodes
- required dependencies (additional to released pom)
- tips for (integration) testing
- how to keep msm quit (for development mode without memcacheds)

Thanx to Carsten Luckmann for this feedback :)

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 12, 2009 09:53:13_

And a link to the spy-memcached logging would be useful
(<a href="https://code.google.com/p/spymemcached/wiki/Logging" rel="nofollow">https://code.google.com/p/spymemcached/wiki/Logging</a>)

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 26, 2009 08:48:08_

Add info/examples regarding the requestUriIgnorePattern

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on August 29, 2009 14:49:05_

Add info on application requirements:
- response must not be committed/closed if memcached-failover shall be supported, as 
this needs to write the cookie to the response at the end of the request processing.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 17, 2009 15:52:23_

The last one (Comment #4) is not valid anymore, because we have the commit hook in 
place.

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 24, 2009 14:37:46_

Mostly done, minor improments (e.g. logging hints) will be added later.

**Summary:** Improve documentation  
  **Status:** Started  
  **Labels:** -Milestone-Release1.0

**Comment by google-code-exporter** [comment]
_From [steph1...@gmail.com](https://code.google.com/u/104678500617310812853/) on February 08, 2011 02:19:04_

Hi Martin,

Inspired by the diagram "scenario1.svg" in "doc" folder, I've written a document describing this session fail-over solution; first of all because I was not convinced I must admit. but I am now.
Is the project interested by such contribution ?

Regards

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 09, 2011 07:34:25_

Definitely, really cool! Drawing some nice stuff is on my list since a long time but everytime I tried I was frustrated of my bad drawing skills :-)

You can just attach the image here and I put it to the wiki, ok?

**Comment by google-code-exporter** [comment]
_From [steph1...@gmail.com](https://code.google.com/u/104678500617310812853/) on February 15, 2011 10:28:15_

I'm not familiar with google code wiki.
I wrote the document under libreoffice. More, some part are still draft.
Maybe you'd like to review it before sharing and maybe it could be 'ported' to the wiki.
I attach a pdf version here.
Tell me.

**Attachment:** [Architecture-session_failover.pdf](http://code.google.com/p/memcached-session-manager/issues/detail?id=12#hc9)

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 16, 2011 12:41:23_

Cool, this looks like an real in-depth work/analysis! Wouldn't you like to publish this on your behalf (as a blog post e.g., or via slideshare.net), and we link to it from the wiki? I think the graphics are great to put them on the home page to visualize memcached/tomcat failover (perhaps slightly modified). What do you think?

**Comment by google-code-exporter** [comment]
_From [steph1...@gmail.com](https://code.google.com/u/104678500617310812853/) on April 27, 2011 08:02:50_

Hi, sorry for the two months delay. It is not that I have enhanced the document a lot. But I've found a location to host it It can be found here <a href="http://blog.fiveinthewood.com/it/tomcat-session-failover/" rel="nofollow">http://blog.fiveinthewood.com/it/tomcat-session-failover/</a>&#13;
I'll be pleased of a review and continue the discussion.&#13;
