### ISSUE TITLE
Create performance test 

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#66]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 25, 2009 01:26:22_

A performance test that shows the difference of tomcat with and w/o the msm 
in terms of response time/throughput.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=22_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on October 27, 2009 09:20:24_

The results are interesting for Christian: 
<a href="http://groups.google.com/group/memcached/browse_thread/thread/1815b6015c0da69f" rel="nofollow">http://groups.google.com/group/memcached/browse_thread/thread/1815b6015c0da69f</a>
