### ISSUE TITLE
msm-javolution-serializer should support deserialization of java.util.Collections$SynchronizedMap

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#73]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on January 04, 2010 00:59:59_

msm-javolution-serializer in version 1.1 seems to not support 
deserialization of java.util.Collections$SynchronizedMap, this fails with:

Jan 4, 2010 12:58:17 AM 
de.javakaffee.web.msm.serializer.javolution.ReflectionFormat readElements
SEVERE: Could not set field value for field protected java.util.Map 
org.apache.catalina.session.StandardSession.attributes
javolution.xml.stream.XMLStreamException caused by 
java.lang.InstantiationException: java.util.Collections$SynchronizedMap
	at javolution.xml.XMLFormat.newInstance(XMLFormat.java:262)
	at 
javolution.xml.XMLFormat$InputElement.readInstanceOf(XMLFormat.java:499)
	at javolution.xml.XMLFormat$InputElement.get(XMLFormat.java:403)

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=29_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on May 24, 2011 14:14:06_

<i>(No comment was entered for this change.)</i>

**Labels:** -Type-Defect Type-Enhancement
