### ISSUE TITLE
Check how session relocation might cause issues with applications bound to the session id

### ISSUE THREAD

**Issue by ghost** [magro/memcached-session-manager#83]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 22, 2010 21:25:10_

Wicket has an AbstractHttpSessionStore.SessionBindingListener class 
(implementing HttpSessionBindingListener and Serializable) that stores the 
session id. When valueUnbound is invoked by the servlet container, the 
SessionBindingListener invokes 
application.getSessionStore().unbind(sessionId) which in turn cleans up the 
PageStore (used by the SecondLevelCacheSessionStore) and the 
bufferedResponses held by the WebApplication.

The question is what does happen when a session is relocated and therefore 
the session id is changed.

_Original issue: http://code.google.com/p/memcached-session-manager/issues/detail?id=39_

**Comment by google-code-exporter** [comment]
_From [martin.grotzke](https://code.google.com/u/martin.grotzke/) on February 22, 2010 12:29:09_

This should also make into some kind of documentation or faq.
